{% set name = "serverfiles" %}
{% set version = "0.3.1" %}
{% set sha256 = "5e10fc32e758791e3735bc08bce2ed4702a83b1e45ab96c5d59cc8aeecfbebe1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - requests >=2.11.1

test:
  imports:
    - serverfiles

about:
  home: https://github.com/biolab/serverfiles/
  license: GPL-3
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'An utility that accesses files on a HTTP server and stores them locally for reuse'

  doc_url: https://serverfiles.readthedocs.io/en/latest/
  dev_url: https://github.com/biolab/serverfiles/

extra:
  recipe-maintainers:
    - astaric
