travis:
  secure:
    BINSTAR_TOKEN: vxhmCE6Mu8QKXEtSWM8E7ubc1E8ktGefxAZKGG47AEwh1r4jWK2xjdln9xEWL46xZDWB0ZEh+qK/3t3T3q4MxXI000Wj/LKDpNRqdoLEUj6ZhyO/q4cN1Z+XScKtmgpkYzA8ADJSAhq4sUyLzuFCXPidPwsyeR2Lln7o/VRAUhe/hjYiQNfUnl/O3WzBt/WmLMBS1r57cG5RuTUsyb4q4nuS7k/1Y1qB+p07Y2I+MjQBShQ7me2se1UerYcyj/WTLuY4FImLg0paMLHNElTGni7GsVCZ/8W9I3VWGxFBg2sHSALqOhFwNo8Y+fOz9qFSB8baQfKQElRKkIlbPfGvem0ROJIAwfbe7KFnI2f6JkCJtnsTAKN+yKgBYqlldxyyGc12MNIUm1S9HDFmeA6t7/V0DTkhCF5mk9frB+4tObv1iRZF9DMdV9/LON6MZEk5HHFae4gErgDqRnGv5lWv0CVSNlHgtFhCbcLulqaBcjhGDoBZC+nzCcPcxwLpOAQlFOCTBcTy/ZS56pZhOtduQYyyc80xFndip1Cea2cEoUxN1QHkRDvg6TF6Rhgs5wWzyEKF7JNJyQ2UnYN6hcQz8rFfYyyTfm+4FvMwUnhN5ny2I2fsr7UVPh+ps458xgiaFLK3fsd/p2IM+bn1iihpw5QAenU6QL+glHLteq25vV0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
