travis:
  secure:
    BINSTAR_TOKEN: hCtsZFs5FeY4hv5GJy9F9Ew2Wi01wrZf/5h2vSezIimS99OQTAwFESpiIlsi7y5xe7EC4/+TxdIgUX2AUZvXqUpPrd0e4KgIXt5zIw3ebymAtgM6jZc+mTys4EInOJ/DtA+J8m2/y6/8vnybTBF5fTId2bW/vW5ay0cnn4SHSiWQI/vjywPPrMb96KTomxtCB+nlYVxEuJ7S26Lge3ljBOyyqcCJHmQtQwIjgQVakcSgYtwtr4idYXn6n2E3mrMF5BdAWeMreFGQKLf3359xDziVjUlh9CukXWu8W9VMTPrEpVADqH/YuNvgojcjWskt3UA2mHcIxOK3ztgg05bx+ClMBCheYxOq3sw+jQ48H6GqWU8uwcaIVyJzFNmIsckXWb+pjApK08sbsQZ3dyiwJB2036Ne1pZbvR/StTv6EaNilEBMjWHmPUWWX/sDJizg9XXsNlvtRJTyhq24NmPYc9dNHp0yAi6t04CDUVafOK0kLtM+Hf8aV228GMTex3bnIcmxS15tBR6KNpijjv8dh4Bxx5bPMIIUuXoiG8UMguR22Cxr4Sz2mI0dAStjKQeBOI32hoxEWjWXp/hNHP1rgyzr0Q8vhcuJztXbUs2HDn68P4oAM1uyHK3zeMBaWjTigMwenbc+zhzvJjHa0qv2nFj86qYx/01SMRAxuXkJ4tI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
